export const CHALLENGE_OPTIONS = [
  {
    challengeId: 1,
    imageSrc: "/man.svg",
    correct: true,
    text: "el hombre",
    audioSrc: "/es_man.mp3",
  },
  {
    challengeId: 1,
    imageSrc: "/woman.svg",
    correct: false,
    text: "la mujer",
    audioSrc: "/es_woman.mp3",
  },
  {
    challengeId: 1,
    imageSrc: "/robot.svg",
    correct: false,
    text: "el robot",
    audioSrc: "/es_robot.mp3",
  },
  {
    challengeId: 2,
    correct: true,
    text: "el hombre",
    audioSrc: "/es_man.mp3",
  },
  {
    challengeId: 2,
    correct: false,
    text: "la mujer",
    audioSrc: "/es_woman.mp3",
  },
  {
    challengeId: 2,
    correct: false,
    text: "el robot",
    audioSrc: "/es_robot.mp3",
  },
  {
    challengeId: 3,
    imageSrc: "/man.svg",
    correct: false,
    text: "el hombre",
    audioSrc: "/es_man.mp3",
  },
  {
    challengeId: 3,
    imageSrc: "/woman.svg",
    correct: false,
    text: "la mujer",
    audioSrc: "/es_woman.mp3",
  },
  {
    challengeId: 3,
    imageSrc: "/robot.svg",
    correct: true,
    text: "el robot",
    audioSrc: "/es_robot.mp3",
  },
  {
    challengeId: 4,
    imageSrc: "/man.svg",
    correct: false,
    text: "el hombre",
    audioSrc: "/es_man.mp3",
  },
  {
    challengeId: 4,
    imageSrc: "/woman.svg",
    correct: true,
    text: "la mujer",
    audioSrc: "/es_woman.mp3",
  },
  {
    challengeId: 4,
    imageSrc: "/robot.svg",
    correct: false,
    text: "el robot",
    audioSrc: "/es_robot.mp3",
  },
];
